In [1]:
# importing modules
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import OrdinalEncoder

In [2]:
# read data
train_data = pd.read_csv("C:/Users/Khadim Rassoul SENE/Documents/MY Datas/Zindi_DSN_Competition/train_data.csv")
test_data = pd.read_csv("C:/Users/Khadim Rassoul SENE/Documents/MY Datas/Zindi_DSN_Competition/test_data.csv")

In [3]:
train_data.head(10)

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim
0,H14663,2013,1.0,0,N,V,V,U,290.0,1,1960.0,.,1053,0
1,H2037,2015,1.0,0,V,N,O,R,490.0,1,1850.0,4,1053,0
2,H3802,2014,1.0,0,N,V,V,U,595.0,1,1960.0,.,1053,0
3,H3834,2013,1.0,0,V,V,V,U,2840.0,1,1960.0,.,1053,0
4,H5053,2014,1.0,0,V,N,O,R,680.0,1,1800.0,3,1053,0
5,H4977,2012,1.0,0,V,N,O,R,535.0,1,1980.0,3,1143,0
6,H7390,2012,1.0,0,N,V,V,U,2830.0,1,1988.0,.,1143,0
7,H14488,2015,1.0,0,N,V,V,U,4952.0,1,1988.0,.,1160,0
8,H19355,2014,1.0,0,V,N,O,R,2735.0,1,2013.0,3,1173,1
9,H18601,2015,1.0,0,V,N,O,R,520.0,1,2011.0,2,1224,0

In [4]:
test_data.head(10)

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code
0,H11920,2013,1.000000,0,V,N,O,R,300.0,1,1960.0,3,3310
1,H11921,2016,0.997268,0,V,N,O,R,300.0,1,1960.0,3,3310
2,H9805,2013,0.369863,0,V,V,V,U,790.0,1,1960.0,.,3310
3,H7493,2014,1.000000,0,V,N,O,R,1405.0,1,2004.0,3,3321
4,H7494,2016,1.000000,0,V,N,O,R,1405.0,1,2004.0,3,3321
5,H10545,2012,1.000000,0,V,V,V,U,3225.0,2,1988.0,.,4070
6,H8962,2015,0.986301,0,N,V,V,U,31.0,2,NaN,.,4070
7,H1015,2013,1.000000,0,V,V,V,U,1400.0,2,1980.0,.,4088
8,H9710,2012,1.000000,0,V,V,V,U,1300.0,2,NaN,.,4094
9,H9029,2012,1.000000,0,N,V,V,U,1200.0,2,NaN,.,4205

In [5]:
# Here we change the customer Id into integer variable
train_data['Customer Id'] = train_data['Customer Id'].apply(lambda s : int(s.strip("H")))
test_data['Customer Id'] = test_data['Customer Id'].apply(lambda s : int(s.strip("H")))

In [6]:
# Here we change the Building_Type variable into a categorical varible
train_data = train_data.astype({'Building_Type': str})
test_data = test_data.astype({'Building_Type': str})

In [7]:
# Getting list of categorical variables
s = (train_data.dtypes == 'object') # gives a series with True and False according to the column type
cat_cols = list(s[s].index) # gives the cat var names
print("Categorical variables:")
print(cat_cols)

Categorical variables:
['Building_Painted', 'Building_Fenced', 'Garden', 'Settlement', 'Building_Type', 'NumberOfWindows', 'Geo_Code']

In [8]:
#instantiate both packages to use
encoder = OrdinalEncoder()
imputer = IterativeImputer(ExtraTreesRegressor())
# create a list of categorical columns to iterate over
cat_cols = ['Building_Painted', 'Building_Fenced', 'Garden', 'Settlement', 'Building_Type', 'NumberOfWindows', 'Geo_Code']

def encode(data):
    '''function to encode non-null data and replace it in the original data'''
    #retains only non-null values
    nonulls = np.array(data.dropna())
    #reshapes the data for encoding
    train_data_reshape = nonulls.reshape(-1,1)
    #encode data
    train_data_ordinal = encoder.fit_transform(train_data_reshape)
    #Assign back encoded values to non-null values
    data.loc[data.notnull()] = np.squeeze(train_data_ordinal)
    return data

#create a for loop to iterate through each column in the data
for columns in cat_cols:
    encode(train_data[columns])

C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [9]:
train_data

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim
0,14663,2013,1.000000,0,0,1,1,1,290.0,0,1960.0,0,7,0
1,2037,2015,1.000000,0,1,0,0,0,490.0,0,1850.0,4,7,0
2,3802,2014,1.000000,0,0,1,1,1,595.0,0,1960.0,0,7,0
3,3834,2013,1.000000,0,1,1,1,1,2840.0,0,1960.0,0,7,0
4,5053,2014,1.000000,0,1,0,0,0,680.0,0,1800.0,3,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7155,5290,2012,1.000000,1,1,1,1,1,NaN,0,2001.0,0,NaN,0
7156,5926,2013,1.000000,0,1,1,1,1,NaN,1,1980.0,0,NaN,1
7157,6204,2016,0.038251,0,1,1,1,1,NaN,0,1992.0,0,NaN,0
7158,6537,2013,1.000000,0,1,1,1,1,NaN,0,1972.0,0,NaN,0
7159,7470,2014,1.000000,0,1,1,1,1,NaN,0,2004.0,0,NaN,0

In [10]:
# impute data and convert 
encode_data = pd.DataFrame(np.round(imputer.fit_transform(train_data)),columns = train_data.columns)

C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\impute\_iterative.py:603: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  " reached.", ConvergenceWarning)

In [11]:
encode_data

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim
0,14663.0,2013.0,1.0,0.0,0.0,1.0,1.0,1.0,290.0,0.0,1960.0,0.0,7.0,0.0
1,2037.0,2015.0,1.0,0.0,1.0,0.0,0.0,0.0,490.0,0.0,1850.0,4.0,7.0,0.0
2,3802.0,2014.0,1.0,0.0,0.0,1.0,1.0,1.0,595.0,0.0,1960.0,0.0,7.0,0.0
3,3834.0,2013.0,1.0,0.0,1.0,1.0,1.0,1.0,2840.0,0.0,1960.0,0.0,7.0,0.0
4,5053.0,2014.0,1.0,0.0,1.0,0.0,0.0,0.0,680.0,0.0,1800.0,3.0,7.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7155,5290.0,2012.0,1.0,1.0,1.0,1.0,1.0,1.0,3687.0,0.0,2001.0,0.0,276.0,0.0
7156,5926.0,2013.0,1.0,0.0,1.0,1.0,1.0,1.0,1683.0,1.0,1980.0,0.0,506.0,1.0
7157,6204.0,2016.0,0.0,0.0,1.0,1.0,1.0,1.0,2374.0,0.0,1992.0,0.0,323.0,0.0
7158,6537.0,2013.0,1.0,0.0,1.0,1.0,1.0,1.0,940.0,0.0,1972.0,0.0,819.0,0.0
7159,7470.0,2014.0,1.0,0.0,1.0,1.0,1.0,1.0,3108.0,0.0,2004.0,0.0,315.0,0.0

In [12]:
encode_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7160 entries, 0 to 7159
Data columns (total 14 columns):
Customer Id           7160 non-null float64
YearOfObservation     7160 non-null float64
Insured_Period        7160 non-null float64
Residential           7160 non-null float64
Building_Painted      7160 non-null float64
Building_Fenced       7160 non-null float64
Garden                7160 non-null float64
Settlement            7160 non-null float64
Building Dimension    7160 non-null float64
Building_Type         7160 non-null float64
Date_of_Occupancy     7160 non-null float64
NumberOfWindows       7160 non-null float64
Geo_Code              7160 non-null float64
Claim                 7160 non-null float64
dtypes: float64(14)
memory usage: 783.2 KB

In [13]:

#instantiate both packages to use
encoder = OrdinalEncoder()
imputer = IterativeImputer(ExtraTreesRegressor())
# create a list of categorical columns to iterate over
cat_cols = ['Building_Painted', 'Building_Fenced', 'Garden', 'Settlement', 'Building_Type', 'NumberOfWindows', 'Geo_Code']

def encode(data):
    '''function to encode non-null data and replace it in the original data'''
    #retains only non-null values
    nonulls = np.array(data.dropna())
    #reshapes the data for encoding
    test_data_reshape = nonulls.reshape(-1,1)
    #encode date
    test_data_ordinal = encoder.fit_transform(test_data_reshape)
    #Assign back encoded values to non-null values
    data.loc[data.notnull()] = np.squeeze(test_data_ordinal)
    return data

#create a for loop to iterate through each column in the data
for columns in cat_cols:
    encode(test_data[columns])

C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [14]:
test_data

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code
0,11920,2013,1.000000,0,1,0,0,0,300.0,0,1960.0,3,142
1,11921,2016,0.997268,0,1,0,0,0,300.0,0,1960.0,3,142
2,9805,2013,0.369863,0,1,1,1,1,790.0,0,1960.0,0,142
3,7493,2014,1.000000,0,1,0,0,0,1405.0,0,2004.0,3,143
4,7494,2016,1.000000,0,1,0,0,0,1405.0,0,2004.0,3,143
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3064,11583,2015,1.000000,0,1,1,1,1,NaN,3,1900.0,0,NaN
3065,11720,2012,1.000000,0,1,1,1,1,NaN,1,1948.0,0,NaN
3066,11721,2012,1.000000,0,1,1,1,1,NaN,1,1993.0,0,NaN
3067,12408,2013,1.000000,0,1,1,1,1,NaN,0,1800.0,0,NaN
3068,9021,2012,1.000000,0,1,1,1,1,NaN,1,1950.0,0,NaN

In [15]:
# impute data and convert 
encode_test_data = pd.DataFrame(np.round(imputer.fit_transform(test_data)),columns = test_data.columns)

C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\impute\_iterative.py:603: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  " reached.", ConvergenceWarning)

In [16]:
encode_test_data

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code
0,11920.0,2013.0,1.0,0.0,1.0,0.0,0.0,0.0,300.0,0.0,1960.0,3.0,142.0
1,11921.0,2016.0,1.0,0.0,1.0,0.0,0.0,0.0,300.0,0.0,1960.0,3.0,142.0
2,9805.0,2013.0,0.0,0.0,1.0,1.0,1.0,1.0,790.0,0.0,1960.0,0.0,142.0
3,7493.0,2014.0,1.0,0.0,1.0,0.0,0.0,0.0,1405.0,0.0,2004.0,3.0,143.0
4,7494.0,2016.0,1.0,0.0,1.0,0.0,0.0,0.0,1405.0,0.0,2004.0,3.0,143.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3064,11583.0,2015.0,1.0,0.0,1.0,1.0,1.0,1.0,1020.0,3.0,1900.0,0.0,440.0
3065,11720.0,2012.0,1.0,0.0,1.0,1.0,1.0,1.0,435.0,1.0,1948.0,0.0,624.0
3066,11721.0,2012.0,1.0,0.0,1.0,1.0,1.0,1.0,2461.0,1.0,1993.0,0.0,164.0
3067,12408.0,2013.0,1.0,0.0,1.0,1.0,1.0,1.0,1776.0,0.0,1800.0,0.0,299.0
3068,9021.0,2012.0,1.0,0.0,1.0,1.0,1.0,1.0,1132.0,1.0,1950.0,0.0,242.0

In [18]:
y = encode_data.Claim
X = encode_data.drop('Claim', axis=1)

In [17]:
encode_test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3069 entries, 0 to 3068
Data columns (total 13 columns):
Customer Id           3069 non-null float64
YearOfObservation     3069 non-null float64
Insured_Period        3069 non-null float64
Residential           3069 non-null float64
Building_Painted      3069 non-null float64
Building_Fenced       3069 non-null float64
Garden                3069 non-null float64
Settlement            3069 non-null float64
Building Dimension    3069 non-null float64
Building_Type         3069 non-null float64
Date_of_Occupancy     3069 non-null float64
NumberOfWindows       3069 non-null float64
Geo_Code              3069 non-null float64
dtypes: float64(13)
memory usage: 311.8 KB

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [20]:
from sklearn.preprocessing import StandardScaler, RobustScaler, QuantileTransformer, PowerTransformer

In [29]:
# From float to int
encode_data['Claim'] = encode_data['Claim'].astype('Int64')

In [30]:
ss = StandardScaler()
rs = RobustScaler()
qt = QuantileTransformer(output_distribution='normal',n_quantiles=891)
yj = PowerTransformer(method = 'yeo-johnson')
bc = PowerTransformer(method = 'box-cox')

In [31]:
ss_data = ss.fit_transform(X)
rs_data = rs.fit_transform(X)
qt_data = qt.fit_transform(X)
yj_data = yj.fit_transform(X)

In [32]:
X_train_f = pd.DataFrame(ss.fit_transform(X_train))
X_test_f = pd.DataFrame(ss.transform(X_test))
test_data_f = pd.DataFrame(ss.transform(encode_test_data))

In [33]:
X_train_f.shape, X_test_f.shape, test_data_f.shape

((5728, 13), (1432, 13), (3069, 13))

In [34]:
print("Fitting random")
print()
model = RandomForestClassifier(n_estimators=1000, random_state=0)
model.fit(X_train_f, y_train)
pred = model.predict(X_test_f)
cm = confusion_matrix(y_test, pred)
print(cm)
print(classification_report(y_test, pred))

Fitting random

[[1027   72]
 [ 242   91]]
              precision    recall  f1-score   support

         0.0       0.81      0.93      0.87      1099
         1.0       0.56      0.27      0.37       333

    accuracy                           0.78      1432
   macro avg       0.68      0.60      0.62      1432
weighted avg       0.75      0.78      0.75      1432

In [35]:
pred_test = model.predict(test_data_f)

In [36]:
# Saving model for test
output = pd.DataFrame({'Customer Id': test_data['Customer Id'].apply(lambda s: 'H'+str(s)),
                       'Claim': pred_test})
output

     Customer Id  Claim
0         H11920    0.0
1         H11921    0.0
2          H9805    0.0
3          H7493    0.0
4          H7494    0.0
...          ...    ...
3064      H11583    0.0
3065      H11720    0.0
3066      H11721    0.0
3067      H12408    0.0
3068       H9021    0.0

[3069 rows x 2 columns]

In [37]:
#output.to_csv('submission_01.csv', index=False)

In [30]:
# USING Robust SCALER rs
X_train_f = pd.DataFrame(rs.fit_transform(X_train))
X_test_f = pd.DataFrame(rs.transform(X_test))
test_data_f = pd.DataFrame(rs.transform(encode_test_data))

In [31]:
print("Fitting random")
print()
model = RandomForestClassifier(n_estimators=1000, random_state=0)
model.fit(X_train_f, y_train)
pred = model.predict(X_test_f)
#print(y_pred)
#y_pred = [0 if i < 0.5 else 1 for i in preds]
cm = confusion_matrix(y_test, pred)
print(cm)
print(classification_report(y_test, pred))

Fitting random

[[1027   72]
 [ 242   91]]
              precision    recall  f1-score   support

         0.0       0.81      0.93      0.87      1099
         1.0       0.56      0.27      0.37       333

    accuracy                           0.78      1432
   macro avg       0.68      0.60      0.62      1432
weighted avg       0.75      0.78      0.75      1432

In [155]:
# Quantile Transformer qt
X_train_f = pd.DataFrame(qt.fit_transform(X_train))
X_test_f = pd.DataFrame(qt.transform(X_test))
test_data_f = pd.DataFrame(qt.transform(encode_test_data))

In [126]:
print("Fitting random")
print()
model = RandomForestClassifier(n_estimators=1000, random_state=0)
model.fit(X_train_f, y_train)
pred = model.predict(X_test_f)
#print(y_pred)
#y_pred = [0 if i < 0.5 else 1 for i in preds]
cm = confusion_matrix(y_test, pred)
print(cm)
print(classification_report(y_test, pred))

Fitting random

[[1029   70]
 [ 246   87]]
              precision    recall  f1-score   support

         0.0       0.81      0.94      0.87      1099
         1.0       0.55      0.26      0.36       333

    accuracy                           0.78      1432
   macro avg       0.68      0.60      0.61      1432
weighted avg       0.75      0.78      0.75      1432

In [127]:
# Power Transformer yj
X_train_f = pd.DataFrame(yj.fit_transform(X_train))
X_test_f = pd.DataFrame(yj.transform(X_test))
test_data_f = pd.DataFrame(yj.transform(encode_test_data))

C:\Users\Khadim Rassoul SENE\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:2863: RuntimeWarning: divide by zero encountered in log
  loglike = -n_samples / 2 * np.log(x_trans.var())

In [51]:
print("Fitting random")
print()
model = RandomForestClassifier(n_estimators=1000, random_state=0)
model.fit(X_train_f, y_train)
pred = model.predict(X_test_f)
#print(y_pred)
#y_pred = [0 if i < 0.5 else 1 for i in preds]
cm = confusion_matrix(y_test, pred)
print(cm)
print(classification_report(y_test, pred))

Fitting random

[[1004   95]
 [ 244   89]]
              precision    recall  f1-score   support

         0.0       0.80      0.91      0.86      1099
         1.0       0.48      0.27      0.34       333

    accuracy                           0.76      1432
   macro avg       0.64      0.59      0.60      1432
weighted avg       0.73      0.76      0.74      1432